name: stroll_bonfire
description: A beautiful social connection app built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.2
  injectable: ^2.5.0
  cached_network_image: ^3.4.1
  blur: ^4.0.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    # SVG files
    - assets/icons/cards.svg
    - assets/icons/chat.svg
    - assets/icons/fire.svg
    - assets/icons/microphone.svg
    - assets/icons/next.svg
    - assets/icons/user.svg
    # PNG files for timer section
    - assets/icons/Timer.png
    - assets/icons/Top-man.png